#!/usr/bin/env python3
import netifaces as ni
import argparse

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument("interface", help="name of the interface")
  args = parser.parse_args()
  
  ip = ni.ifaddresses(args.interface)[ni.AF_INET][0]['addr']
  print (ip)  
