#!/usr/bin/env python3
import os
import yaml
import argparse
import sys

# get parameter file and return specific value requested or return all values if nothing requested
params=None
path='/etc/opparams'

def readFile():
	if os.path.exists(path):
		with open(path, 'rt') as f:
			global params
			params = yaml.safe_load(f.read())
	else:
		print ('no params file found')

if __name__ == '__main__':
	readFile()
	parser = argparse.ArgumentParser()
	parser.add_argument("name", help="the name of the property to get")
	args = parser.parse_args()

	# check if the name is in property list
	if args.name in params:
		print(params[args.name])
		sys.exit(0)
	else:
		sys.exit(1)

