#!/usr/bin/env python3
import os
import yaml
import argparse
import sys

# set parameter in parameter file
params=None
path='/etc/rmparams'

def readFile():
	if os.path.exists(path):
		with open(path, 'rt') as f:
			global params
			params = yaml.safe_load(f.read())
	else:
		print ('no params file found')
		sys.exit(1)

def writeFile():
	with open(path, 'w') as f:
		yaml.dump(params,f,default_flow_style=False)

if __name__ == '__main__':
	readFile()
	parser = argparse.ArgumentParser()
	parser.add_argument("name", help="the name of the property to set")
	parser.add_argument("value", help="the value of the property to set")
	args = parser.parse_args()

	# check if the name is in property list
	if args.name in params:
		params[args.name]=args.value
		writeFile()
		sys.exit(0)
	else:
		sys.exit(1)